### ISSUE TITLE
declarations in header files need "C" linkage

### ISSUE THREAD

**Issue by sarah-quinones** [Benny44/QPALM_vLADEL#7]
header files should be prefixed with
```cpp
# ifdef __cplusplus
extern "C" {
# endif // ifdef __cplusplus
```
and suffixed with
```cpp
#ifdef __cplusplus
}
# endif // ifdef __cplusplus
```
so that the library may be compatible with C++ code including it. otherwise this results in a linker error when the symbols aren't found.

**Comment by Benny44** [comment]
Should be fixed, can you confirm so I can close the issue? Thanks.

**Comment by sarah-quinones** [comment]
works as expected. thanks!

**Comment by Benny44** [comment]
You're welcome. Thanks for the contribution.
